version: '3'
services:
  remote-apps:
    image: nginx
    ports:
      - 4000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./remotes/remote1/build:/usr/share/nginx/html/remote1
      - ./remotes/remote2/build:/usr/share/nginx/html/remote2
      - ./remotes/admin/build:/usr/share/nginx/html/admin
      - ./remotes/deployment.json:/usr/share/nginx/html/deployment.json
  mysql:
    platform: linux/amd64
    image: amd64/mysql:8
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql

  mysqladmin:
    platform: linux/amd64
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
